import type { PostFilter } from "./utils/posts";

export interface SiteConfig {
  title: string;
  slogan: string;
  description?: string;
  site: string,
  social: {
    github?: string;
    linkedin?: string;
    email?: string;
    rss?: boolean;
  };
  homepage: PostFilter;
  googleAnalysis?: string;
  search?: boolean;
}

export const siteConfig: SiteConfig = {
  site: "https://blog.raulnq.win/", // your site url
  title: "Raul's blog",
  slogan: "Someone who enjoys coding",
  description: "Personal blog with content mostly generated by AI for educational purposes.",
  social: {
    github: "https://github.com/raulnq", // leave empty if you don't want to show the github
    linkedin: "https://www.linkedin.com/in/raulnq", // leave empty if you don't want to show the linkedin
    email: "raulnq@gmail.com", // leave empty if you don't want to show the email
    rss: true, // set this to false if you don't want to provide an rss feed
  },
  homepage: {
    maxPosts: 5,
    tags: [],
    excludeTags: [],
  },
  googleAnalysis: "", // your google analysis id
  search: true, // set this to false if you don't want to provide a search feature
};
